---
title: configure-win32priorityseparation
description: configure-win32priorityseparation
privilege: TrustedInstaller
actions:

    # --- Quantum is the amount of time the Windows process scheduler allocates to a thread. There are two recommended values:
    # -----> 26/38 - Short Quantum, variable, 3x foreground boost
    # -----> 16/22 - Long Quantum, variable, 3x foreground boost
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\PriorityControl', value: 'Win32PrioritySeparation', type: REG_DWORD, data: '38'}
