---
title: Services
description: Removal and configuration of services
privilege: TrustedInstaller
actions:
  
    # === Beep - Disabled
  - !service: {name: 'Beep', operation: change, startup: 4}
    # === GraphicsPerfSvc - Disabled
  - !service: {name: 'GraphicsPerfSvc', operation: change, startup: 4}
    # === Desktop Activity Moderator Driver - Disabled
  - !service: {name: 'dam', operation: change, startup: 4}
    # === Background Activity Moderator Driver - Disabled
  - !service: {name: 'bam', operation: change, startup: 4}
    # === GPU Energy Driver - Disabled
  - !service: {name: 'GpuEnergyDrv', operation: change, startup: 4}
    # === NetBT - Disabled
  - !service: {name: 'NetBT', operation: change, startup: 4}
    # === Intel(R) Telemetry Service - Disabled
  - !service: {name: 'Telemetry', operation: change, startup: 4}

    # === Windows Network Data Usage Monitoring Driver - Disabled
  - !service: {name: 'Ndu', operation: change, startup: 4}
    # === Microsoft (R) Diagnostics Hub Standard Collector Service - Disabled
  - !service: {name: 'diagnosticshub.standardcollector.service', operation: change, startup: 4}
    # === Windows Error Reporting Service - Disabled
  - !service: {name: 'WerSvc', operation: change, startup: 4}
    # === Unified Telemetry Client - Disabled
  - !service: {name: 'DiagTrack', operation: change, startup: 4}
    # === Windows Insider Service - Disabled
  - !service: {name: 'wisvc', operation: change, startup: 4}
    # === Program Compatibility Assistant Service - Disabled
  - !service: {name: 'PcaSvc', operation: change, startup: 4}
    # === Diagnostic Policy Service - Disabled
    # ------> Needed for Data usage and troubleshooting, but the Troubleshooter automatically activates the service itself when needed
  - !service: {name: 'DPS', operation: change, startup: 4}
    # === Diagnostic Service Host - Disabled
  - !service: {name: 'WdiServiceHost', operation: change, startup: 4}
    # === Diagnostic System Host - Disabled
  - !service: {name: 'WdiSystemHost', operation: change, startup: 4}
  
    # == Tcpipreg (experimental)
  - !service: {name: 'tcpipreg', operation: change, startup: 4}
    # == EdgeUpdate - Manual (Disabled breaks WebView installation via Visual Studio)
  - !service: {name: 'edgeupdate', operation: change, startup: 3}

  # == Windows Event Collector - Disabled
  - !service: {name: 'Wecsvc', operation: change, startup: 4} 

  # == Other
  - !service: {name: 'lfsvc', operation: change, startup: 4}
  - !service: {name: 'MapsBroker', operation: change, startup: 4}
  - !service: {name: 'OneSyncSvc', operation: change, startup: 4}
  - !service: {name: 'TrkWks', operation: change, startup: 4}
  - !service: {name: 'PcaSvc', operation: change, startup: 4}
  - !service: {name: 'DiagTrack', operation: change, startup: 4}
  - !service: {name: 'WSearch', operation: change, startup: 4}