---
title: configure-logon
description: configure-logon
privilege: TrustedInstaller
actions:

    # =============
    # === Logon ===
    # =============
    # === Always use classic logon - Disabled
    # ------> Outdated tweak
    # [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System]
    # "LogonType"=dword:00000001
    # === Show first sign-in animation - Disabled
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'EnableFirstLogonAnimation', type: REG_DWORD, data: '0'}
    # === Turn off app notifications on the lock screen - Disabled
    # ------> Defaulted due to removal of subjective changes.
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows\System', value: 'DisableLockScreenAppNotifications', type: REG_DWORD, data: '0'}
    # === Turn off Windows Startup sound - Enabled
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'DisableStartupSound', type: REG_DWORD, data: '1'}
    # ========================================
    # === Control Panel -> Personalization ===
    # ========================================
    # === Do not display the lock screen - Enabled
    # ------> This won't skip the password/pin screen.
    # [HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Personalization]
    # "NoLockScreen"=dword:00000001
    # =============================
    # === Windows Logon Options ===
    # =============================
    # === Sign-in and lock last interactive user automatically after a restart - Disabled
    # ------> Prevents apps from automatically reopening after a restart or an update.
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'DisableAutomaticRestartSignOn', type: REG_DWORD, data: '1'}
    # ==============
    # === System ===
    # ==============
    # === Display highly detailed status messages - Disabled
    # ------> Makes it easier to debug when running into reboot/shutdown/startup errors.
    # ------> Defaulted due to removal of subjective changes.
  - !registryValue: {path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System', value: 'VerboseStatus', type: REG_DWORD, data: '0'}
