---
title: configure-security
description: configure-security
privilege: TrustedInstaller
actions:
    # ==========================
    # === Mitigation Options ===
    # ==========================
    # === Process Mitigation Options - Disabled
    # ------> Disables Process Mitigations on csrss, dwm and ntoskrnl
    # ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.GroupPolicy::ProcessMitigationOptions
    # ------> https://argonsys.com/microsoft-cloud/library/windows-10-memory-protection-features/
  - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows NT\MitigationOptions\ProcessMitigationOptions', value: 'csrss.exe', type: REG_SZ, data: '00000000000000000000000000000000'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows NT\MitigationOptions\ProcessMitigationOptions', value: 'dwm.exe', type: REG_SZ, data: '00000000000000000000000000000000'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows NT\MitigationOptions\ProcessMitigationOptions', value: 'ntoskrnl.exe', type: REG_SZ, data: '00000000000000000000000000000000'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\MitigationOptions\ProcessMitigationOptions', value: 'csrss.exe', type: REG_SZ, data: '00000000000000000000000000000000'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\MitigationOptions\ProcessMitigationOptions', value: 'dwm.exe', type: REG_SZ, data: '00000000000000000000000000000000'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\MitigationOptions\ProcessMitigationOptions', value: 'ntoskrnl.exe', type: REG_SZ, data: '00000000000000000000000000000000'}
    # ==============================================
    # === Windows Defender Antivirus - Reporting ===
    # ==============================================
    # === Configure Watson events - Disabled
    # ------> https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Reporting', value: 'DisableGenericRePorts', type: REG_DWORD, data: '1'}
    # ==================================================================
    # === Windows Defender Antivirus - Security Intelligence Updates ===
    # ==================================================================
    # === Allow notifications to disable security intelligence based reports to Microsoft MAPS - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates', value: 'SignatureDisableNotification', type: REG_DWORD, data: '0'}
    # === Allow real-time security intelligence updates based on reports to Microsoft MAPS - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates', value: 'RealtimeSignatureDelivery', type: REG_DWORD, data: '0'}
    # === Allow security intelligence updates from Microsoft Update - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates', value: 'ForceUpdateFromMU', type: REG_DWORD, data: '0'}
    # === Allow security intelligence updates when running on battery power - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates', value: 'DisableScheduledSignatureUpdateOnBattery', type: REG_DWORD, data: '1'}
    # === Check for the latest virus and spyware security intelligence on startup - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates', value: 'UpdateOnStartUp', type: REG_DWORD, data: '0'}
    # === Initiate security intelligence update on startup - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates', value: 'DisableUpdateOnStartupWithoutEngine', type: REG_DWORD, data: '1'}
    # === Turn on scan after security intelligence update - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates', value: 'DisableScanOnUpdate', type: REG_DWORD, data: '1'}
    # ====================================
    # === Windows Defender SmartScreen ===
    # ====================================
    # === Configure App Install Control - Enabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\SmartScreen', value: 'ConfigureAppInstallControlEnabled', type: REG_DWORD, data: '1'}
    # === Pick one of the following settings - Turn off app recommendations
    # ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.SmartScreen::ConfigureAppInstallControl
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\Windows Defender\SmartScreen', value: 'ConfigureAppInstallControl', type: REG_SZ, data: 'Anywhere'}
    # === Configure Windows Defender SmartScreen - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\System', value: 'EnableSmartScreen', type: REG_DWORD, data: '0'}
  # - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\smartscreen.exe', value: 'Debugger', type: REG_SZ, data: '%windir%\System32\taskkill.exe'}
    # === Configure Windows Defender SmartScreen (Microsoft Edge) - Disabled
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\MicrosoftEdge\PhishingFilter', value: 'EnabledV9', type: REG_DWORD, data: '0'}
    # ========================
    # === Windows Security ===
    # ========================
    # === Hide Windows Security Systray - Enabled
    # ------> https://www.tenforums.com/tutorials/11974-hide-show-windows-security-notification-area-icon-windows-10-a.html
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Systray', value: 'HideSystray', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run', value: 'SecurityHealth', operation: delete}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run', operation: add}
    # === https://learn.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10#bitlocker-device-encryption
  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\BitLocker', value: 'PreventDeviceEncryption', type: REG_DWORD, data: '1'}