---
title: configure-microsoft-store
description: configure-microsoft-store
privilege: TrustedInstaller
actions:

    # === Turn off Automatic Download and Install of updates - Disabled
    # ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsStore::DisableAutoInstall
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\WindowsStore', value: 'AutoDownload', type: REG_DWORD, data: '4'}
    # === Turn off the offer to update to the latest version of Windows - Enabled
  - !registryValue: {path: 'HKCU\Software\Policies\Microsoft\WindowsStore', value: 'DisableOSUpgrade', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\Software\Policies\Microsoft\WindowsStore', value: 'DisableOSUpgrade', type: REG_DWORD, data: '1'}
